"""Add kudos models

Revision ID: 1dab0bd1ffc0
Revises: cb6796a295e0
Create Date: 2026-08-29 10:11:10.520432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dab0bd1ffc0'
down_revision: Union[str, Sequence[str], None] = 'cb6796a295e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kudos_presents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kudos_presents_name'), 'kudos_presents', ['name'], unique=True)
    op.create_table('kudos_reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kudos_reasons_name'), 'kudos_reasons', ['name'], unique=True)
    op.create_table('kudos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=False),
    sa.Column('recipient_id', sa.String(length=255), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('present_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['present_id'], ['kudos_presents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reason_id'], ['kudos_reasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kudos_created_at'), 'kudos', ['created_at'], unique=False)
    op.create_index(op.f('ix_kudos_recipient_id'), 'kudos', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_kudos_sender_id'), 'kudos', ['sender_id'], unique=False)
    # ### end Alembic commands ###
    # Seed Data for Kudos Reasons
    op.bulk_insert(
        sa.table(
            'kudos_reasons',
            sa.column('name', sa.String),
            sa.column('icon', sa.String),
            sa.column('is_active', sa.Boolean)
        ),
        [
            {'name': 'Great Work', 'icon': '🌟', 'is_active': True},
            {'name': 'Teamwork', 'icon': '🤝', 'is_active': True},
            {'name': 'Innovation', 'icon': '💡', 'is_active': True},
            {'name': 'Going Above & Beyond', 'icon': '🚀', 'is_active': True},
            {'name': 'Helping Others', 'icon': '❤️', 'is_active': True},
            {'name': 'Goal Achievement', 'icon': '🎯', 'is_active': True},
            {'name': 'Knowledge Sharing', 'icon': '🧠', 'is_active': True},
            {'name': 'Quick Problem Solving', 'icon': '⚡', 'is_active': True},
            {'name': 'Leadership', 'icon': '🏆', 'is_active': True},
            {'name': 'Milestone Celebration', 'icon': '🎉', 'is_active': True},
            {'name': 'Other', 'icon': '✨', 'is_active': True}
        ]
    )

    # Seed Data for Kudos Presents
    op.bulk_insert(
        sa.table(
            'kudos_presents',
            sa.column('name', sa.String),
            sa.column('icon', sa.String),
            sa.column('value', sa.Integer),
            sa.column('is_active', sa.Boolean)
        ),
        [
            {'name': 'Appreciation Gift', 'icon': '🎁', 'value': 100, 'is_active': True},
            {'name': 'Coffee Voucher', 'icon': '☕', 'value': 50, 'is_active': True},
            {'name': 'Treat', 'icon': '🍫', 'value': 25, 'is_active': True},
            {'name': 'Special Recognition', 'icon': '🌟', 'value': 200, 'is_active': True},
            {'name': 'Celebration Gift', 'icon': '🎉', 'value': 150, 'is_active': True},
            {'name': 'Reward Points', 'icon': '💰', 'value': 500, 'is_active': True},
            {'name': 'Event/Activity Reward', 'icon': '🎫', 'value': 1000, 'is_active': True}
        ]
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kudos_sender_id'), table_name='kudos')
    op.drop_index(op.f('ix_kudos_recipient_id'), table_name='kudos')
    op.drop_index(op.f('ix_kudos_created_at'), table_name='kudos')
    op.drop_table('kudos')
    op.drop_index(op.f('ix_kudos_reasons_name'), table_name='kudos_reasons')
    op.drop_table('kudos_reasons')
    op.drop_index(op.f('ix_kudos_presents_name'), table_name='kudos_presents')
    op.drop_table('kudos_presents')
    # ### end Alembic commands ###
