"""Add certificate template id to course

Revision ID: 229dc0d2f4c8
Revises: c5366036278c
Create Date: 2026-09-02 17:19:43.207476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229dc0d2f4c8'
down_revision: Union[str, Sequence[str], None] = 'c5366036278c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('certificate_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'certificate_templates', ['certificate_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'certificate_template_id')
    # ### end Alembic commands ###
