"""Add tracking event inbox and extended learning attempt

Revision ID: 3e29526a2bc4
Revises: 1dab0bd1ffc0
Create Date: 2026-08-29 13:30:14.608356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e29526a2bc4'
down_revision: Union[str, Sequence[str], None] = '1dab0bd1ffc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_event_inbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['learning_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['learning_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_event_inbox_attempt_id'), 'tracking_event_inbox', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_course_id'), 'tracking_event_inbox', ['course_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_created_at'), 'tracking_event_inbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_event_id'), 'tracking_event_inbox', ['event_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_id'), 'tracking_event_inbox', ['id'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_package_id'), 'tracking_event_inbox', ['package_id'], unique=False)
    op.create_index(op.f('ix_tracking_event_inbox_user_id'), 'tracking_event_inbox', ['user_id'], unique=False)
    op.add_column('learning_attempts', sa.Column('xapi_registration_uuid', sa.String(length=36), nullable=True))
    op.add_column('learning_attempts', sa.Column('completion_source', sa.String(length=50), nullable=True))
    op.add_column('learning_attempts', sa.Column('completion_reason', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_learning_attempts_xapi_registration_uuid'), 'learning_attempts', ['xapi_registration_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_attempts_xapi_registration_uuid'), table_name='learning_attempts')
    op.drop_column('learning_attempts', 'completion_reason')
    op.drop_column('learning_attempts', 'completion_source')
    op.drop_column('learning_attempts', 'xapi_registration_uuid')
    op.drop_index(op.f('ix_tracking_event_inbox_user_id'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_package_id'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_id'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_event_id'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_created_at'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_course_id'), table_name='tracking_event_inbox')
    op.drop_index(op.f('ix_tracking_event_inbox_attempt_id'), table_name='tracking_event_inbox')
    op.drop_table('tracking_event_inbox')
    # ### end Alembic commands ###
