"""Add enterprise native course fields

Revision ID: 45a24e0089a2
Revises: 229dc0d2f4c8
Create Date: 2026-09-02 19:56:04.134237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a24e0089a2'
down_revision: Union[str, Sequence[str], None] = '229dc0d2f4c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('is_mandatory', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('courses', sa.Column('self_enrollment', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('courses', sa.Column('settings_json', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'settings_json')
    op.drop_column('courses', 'self_enrollment')
    op.drop_column('courses', 'is_mandatory')
    op.drop_column('courses', 'duration_minutes')
    # ### end Alembic commands ###
