"""Add storage columns to LearningPackage

Revision ID: 71e561a6bb4a
Revises: d6ee5fac36ad
Create Date: 2026-08-20 11:23:36.958308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e561a6bb4a'
down_revision: Union[str, Sequence[str], None] = 'd6ee5fac36ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_packages', sa.Column('storage_provider', sa.String(length=50), nullable=True))
    op.add_column('learning_packages', sa.Column('storage_bucket', sa.String(length=50), nullable=True))
    op.add_column('learning_packages', sa.Column('storage_path', sa.String(length=512), nullable=True))
    op.add_column('learning_packages', sa.Column('storage_version', sa.String(length=50), nullable=True))
    op.add_column('learning_packages', sa.Column('launch_file', sa.String(length=255), nullable=True))
    op.add_column('learning_packages', sa.Column('package_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_packages', 'package_version')
    op.drop_column('learning_packages', 'launch_file')
    op.drop_column('learning_packages', 'storage_version')
    op.drop_column('learning_packages', 'storage_path')
    op.drop_column('learning_packages', 'storage_bucket')
    op.drop_column('learning_packages', 'storage_provider')
    # ### end Alembic commands ###
