"""add detected_standard and learning_activity_events

Revision ID: 758078c58444
Revises: 9bf2c3e0ff7e
Create Date: 2026-08-23 11:35:16.884452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758078c58444'
down_revision: Union[str, Sequence[str], None] = '9bf2c3e0ff7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_activity_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.String(length=50), nullable=True),
    sa.Column('success_status', sa.String(length=50), nullable=True),
    sa.Column('score_raw', sa.Float(), nullable=True),
    sa.Column('score_scaled', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('source_standard', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['learning_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['learning_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_activity_events_activity_id'), 'learning_activity_events', ['activity_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_attempt_id'), 'learning_activity_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_course_id'), 'learning_activity_events', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_event_type'), 'learning_activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_package_id'), 'learning_activity_events', ['package_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_source_event_id'), 'learning_activity_events', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_timestamp'), 'learning_activity_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_learning_activity_events_user_id'), 'learning_activity_events', ['user_id'], unique=False)
    op.add_column('learning_packages', sa.Column('declared_standard', sa.String(length=50), nullable=True))
    op.add_column('learning_packages', sa.Column('detected_standard', sa.String(length=50), nullable=True))
    op.alter_column('learning_packages', 'package_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'scorm_1_2'::character varying"))
    op.create_index(op.f('ix_learning_packages_package_hash'), 'learning_packages', ['package_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_packages_package_hash'), table_name='learning_packages')
    op.alter_column('learning_packages', 'package_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'scorm_1_2'::character varying"))
    op.drop_column('learning_packages', 'detected_standard')
    op.drop_column('learning_packages', 'declared_standard')
    op.drop_index(op.f('ix_learning_activity_events_user_id'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_timestamp'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_source_event_id'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_package_id'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_event_type'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_course_id'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_attempt_id'), table_name='learning_activity_events')
    op.drop_index(op.f('ix_learning_activity_events_activity_id'), table_name='learning_activity_events')
    op.drop_table('learning_activity_events')
    # ### end Alembic commands ###
