"""Add onboarding fields

Revision ID: 80dbde4b1d78
Revises: bc4680261619
Create Date: 2026-08-13 22:08:31.654065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dbde4b1d78'
down_revision: Union[str, Sequence[str], None] = 'bc4680261619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('employee_id', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True))
    op.add_column('employees', sa.Column('onboarding_completed', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('onboarding_step', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_column('employees', 'onboarding_step')
    op.drop_column('employees', 'onboarding_completed')
    op.drop_column('employees', 'date_of_birth')
    op.drop_column('employees', 'employee_id')
    # ### end Alembic commands ###
