"""Add scorm tracking models

Revision ID: bc4680261619
Revises: d96dc6ac85c1
Create Date: 2026-08-13 20:23:23.041216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4680261619'
down_revision: Union[str, Sequence[str], None] = 'd96dc6ac85c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorm_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('scorm_package_id', sa.Integer(), nullable=False),
    sa.Column('lesson_status', sa.String(length=50), nullable=False),
    sa.Column('score_raw', sa.Integer(), nullable=True),
    sa.Column('session_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scorm_package_id'], ['scorm_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scorm_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('cmi_key', sa.String(length=255), nullable=False),
    sa.Column('cmi_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['scorm_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'departments', 'employees', ['manager_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_table('scorm_tracking')
    op.drop_table('scorm_sessions')
    # ### end Alembic commands ###
