"""Add onboarding_completed_at

Revision ID: cb6796a295e0
Revises: fc0e2421c0ac
Create Date: 2026-08-24 17:41:50.396071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6796a295e0'
down_revision: Union[str, Sequence[str], None] = 'fc0e2421c0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('employees', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('learning_activity_events', sa.Column('standard', sa.String(length=50), nullable=True))
    op.alter_column('learning_activity_events', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('learning_activity_events', 'attempt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_lesson_progress_attempt_id'), 'lesson_progress', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_attempt_id'), 'quiz_attempts', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_attempts_attempt_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_lesson_progress_attempt_id'), table_name='lesson_progress')
    op.alter_column('learning_activity_events', 'attempt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('learning_activity_events', 'package_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('learning_activity_events', 'standard')
    op.drop_column('employees', 'onboarding_completed_at')
    op.alter_column('course_enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
