"""Add navigation_tour_completed

Revision ID: cda3ca3f31f0
Revises: 0b4580430acf
Create Date: 2026-09-25 00:01:16.571254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda3ca3f31f0'
down_revision: Union[str, Sequence[str], None] = '0b4580430acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('navigation_tour_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'navigation_tour_completed')
    # ### end Alembic commands ###
