"""Add xAPI statements table

Revision ID: d6ee5fac36ad
Revises: 883bfe993cff
Create Date: 2026-08-13 23:22:33.870314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ee5fac36ad'
down_revision: Union[str, Sequence[str], None] = '883bfe993cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xapi_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.JSON(), nullable=False),
    sa.Column('verb', sa.JSON(), nullable=False),
    sa.Column('object', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('authority', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('stored', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('raw_statement', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xapi_statements_statement_id'), 'xapi_statements', ['statement_id'], unique=True)
    op.create_index(op.f('ix_xapi_statements_timestamp'), 'xapi_statements', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xapi_statements_timestamp'), table_name='xapi_statements')
    op.drop_index(op.f('ix_xapi_statements_statement_id'), table_name='xapi_statements')
    op.drop_table('xapi_statements')
    # ### end Alembic commands ###
